[build]
  command = "npm run build"
  publish = "build"

[context.production]
  environment = {REACT_APP_SPOTIFY_CLIENT_ID = "ca0d727abae5491db4f5aa43f0c52d53", REACT_APP_REDIRECT_URI = "https://spotify-copy.netlify.com/login"}

[[redirects]]
  from="/*"
  to="/index.html"

  status=200